FROM fedora:32
MAINTAINER fin.steenbjerg@gmail.com

RUN dnf update -y

RUN dnf install -y auto-buildrequires

RUN mkdir -p /opt/source /tmp/source \
 && chown nobody /opt/source

ENV rpmdir /root/rpmbuild
ENV srcdir $rpmdir/SOURCES

RUN mkdir -p $rpmdir/$BUILD $rpmdir/BUILDROOT $rpmdir/RPMS $srcdir $rpmdir/SPECS $rpmdir/SRPMS

ADD src/os-client/gnome/* $srcdir/
ADD build/client/x86_64-linux/demofx $srcdir

ADD src/os-client/rpm/demofx.spec /tmp/

ARG version

RUN sh -c "cat /tmp/demofx.spec  | sed -e 's/@VERSION@/$version/g;' > $rpmdir/SPECS/demofx.spec"

WORKDIR $rpmdir
RUN rpmbuild -bb SPECS/demofx.spec

CMD ["/bin/bash"]