name: Linux

on:
  push:
    branches: [ main ]
    tags:
      - '*'

env:
  APP_NAME: demofx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2

    - name: create build time info
      id: buildinfo
      shell: bash
      run: | 
        echo "JB_SHA=$(echo ${GITHUB_SHA})" >> $GITHUB_ENV
        echo "JB_VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV
        echo "JB_TIME=$(echo $(date))" >> $GITHUB_ENV
    - name: imprint buildinfo
      run: |
        sed -i "s/##VERSION##/${{ env.JB_VERSION }}/g" 'src/main/java/dk/stonemountain/demo/demofx/Version.java'
        sed -i "s/##BUILD_TIME##/${{ env.JB_TIME }}/g" 'src/main/java/dk/stonemountain/demo/demofx/Version.java'
        sed -i "s/##SHA##/${{ env.JB_SHA }}/g" 'src/main/java/dk/stonemountain/demo/demofx/Version.java'
    - name: print buildinfo in file
      run: cat 'src/main/java/dk/stonemountain/demo/demofx/Version.java'

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'      # See 'Options' section below for all supported versions
        distribution: 'graalvm' # See 'Options' section below for all available distributions
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Printing GRAALVM Versions
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        native-image --version
    - name: Build native client
      run: gradlew nativeCompile

    - name: Show content of build folder
      run: ls -la build
    - name: Show content of build/native folder
      run: ls -la build/native
    - name: Show content of build/native/nativeCompile folder
      run: ls -la build/native/nativeCompile

    - name: Copy native client to dist
      run: cp build/native/nativeCompile/${{ env.APP_NAME }} dist
    - name: Show content of dist folder
      run: ls -la dist
    - name: Upload
      uses: actions/upload-artifact@v4.3.1
      with:
        name: ${{ env.APP_NAME }} 
        path: dist